# Generated by Django 2.1.2 on 2018-10-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('account', models.CharField(max_length=20)),
                ('passwd', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=20)),
                ('checkCode', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
