# Generated by Django 2.1.2 on 2018-10-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, null=True)),
                ('account', models.CharField(max_length=20)),
                ('passwd', models.CharField(max_length=20)),
                ('token', models.CharField(default=' ', max_length=256, null=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
