# Generated by Django 2.1.2 on 2018-10-28 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='checkCode',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tel',
        ),
    ]
