# Generated by Django 2.1.2 on 2018-10-28 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20181028_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default=None, max_length=80, null=True),
        ),
    ]
